### ISSUE TITLE
Unable to import Pyhcrf

### ISSUE THREAD

**Issue by sanyam1997** [dirko/pyhcrf#5]
I am having python 2.7 along with updated versions of cython , numpy and scipy. Despite that i am unable to import Pyhcrf because of undefined symbol in a file named algortithm.so which i am unable to edit. Please suggest some solution soon.
Error : 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyhcrf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pyhcrf/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pyhcrf/hcrf.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/pyhcrf/algorithms.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pyhcrf/algorithms.py", line 6, in __bootstrap__
ImportError: /home/hp/.cache/Python-Eggs/pyhcrf-0.0.1-py2.7-linux-x86_64.egg-tmp/pyhcrf/algorithms.so: undefined symbol: npy_logaddexp

**Comment by dirko** [comment]
Could you maybe post the versions of cython, numpy, and scipy? I'll then check whether I can reproduce - otherwise I'll update the requirements file.

**Comment by ChemsEddineBerbegue** [comment]
@dirko, I am facnig the same problem, could you please share us the version of the used: numpy, scipy  
, cython.

**Comment by ChemsEddineBerbegue** [comment]
I  share them: 
numpy: 1.12.1
scipy: 0.18.1
cython: 0.25.2
